### ISSUE TITLE
Unexpected behavior for prepared data input

### ISSUE THREAD

**Issue by AlekseiVereshchagin** [farmovit/streamMonitor#1]
`streamMonitor` is launched with redirected input from the prepared file (~1KB size) with content like:

```
111
222
333
...
```

_Expected behavior_

See the output data by **80**-character groups per second. End of line should not be used between groups.

_Observed behavior_

See all the output data at once.

**Comment by farmovit** [comment]
It should be fixed. Please, check it out.

**Comment by AlekseiVereshchagin** [comment]
6a1700d

It doesn't help with line length (80 character required) and end of line presence between outputs (only original lines concatenated with space should be printed).

Why program should check tty input? It just handle input, print it with speed 80 chars per second and finish work on all data handled or earlier on errors or signal interruption.

Could you open pull request to handle this issue and don't merge it until issue will be done?

**Comment by AlekseiVereshchagin** [comment]
Empty line isn't a condition for program interruption.

**Comment by farmovit** [comment]
I got you.

> Could you open pull request to handle this issue and don't merge it until issue will be done?

Ok, I created a pull request. Please, check it out.

**Comment by AlekseiVereshchagin** [comment]
What will happen if this program handle an input file redirected to the standard input? Will I see the output portion by portion (with rate 80 characters per second) until all processed data will be printed?

**Comment by farmovit** [comment]
Yes, you will. I double checked it by following commands:
`./streamMonitor < content`
`cat content | ./streamMonitor`

**Comment by AlekseiVereshchagin** [comment]
Maybe, I will check. But at least according to this code `Buffer::popFront()` takes `num - 1`, not `num` characters.

https://github.com/farmovit/streamMonitor/blob/6a1700d90b9a65a3298007e5b3e5db7a2f2f5bf1/src/Buffer.cpp#L11-L12

And here end of line printed for each data portion.

https://github.com/farmovit/streamMonitor/blob/6a1700d90b9a65a3298007e5b3e5db7a2f2f5bf1/src/StreamMonitorApp.cpp#L62-L72

**Comment by farmovit** [comment]
Oh. I got, what do you mean. I need to rework it.
I thought I should print end of line after every printed line.

**Comment by AlekseiVereshchagin** [comment]
No, output is just lines concatination with space character, but it should printed with some restricted rate. End of line should only be applied as last output character if any data were printed.

**Comment by farmovit** [comment]
Updated PR
